### ISSUE TITLE
Should be republished with package.json with a main field

### ISSUE THREAD

**Issue by charandas** [thorst/jquery-idletimer#44]
I noticed that package.json currently has a `main` field as prescribed, however a new tag is not published.

Would help with using with jspm and like.

**Comment by thorst** [comment]
can you create a pull

**Comment by charandas** [comment]
Yes, will do this evening.

**Comment by charandas** [comment]
@thorst  The pjson already has a `main` property. What we need is a republished git tag for `1.1.0`.
https://github.com/thorst/jquery-idletimer/blob/master/package.json#L3

Not sure why the version in pjson is set to ignored. Shouldn't it track the version of the library, even if its not published to npm.
https://github.com/thorst/jquery-idletimer/blob/master/package.json#L4

I can send a PR for that, if you wish.

**Comment by thorst** [comment]
Do what's you need/think. I probably copied somewhere without knowing​ what
it was.

**Comment by charandas** [comment]
Sent [pull](https://github.com/thorst/jquery-idletimer/pull/45)

**Comment by charandas** [comment]
@thorst It still hasn't been tagged since the last merge. Once tagged, it would show [here](https://github.com/thorst/jquery-idletimer/releases).

**Comment by thorst** [comment]
Yeah, sorry, work has been crazy. 1.0.2 just tagged

**Comment by charandas** [comment]
No problem. Great.
