### ISSUE TITLE
Support Multiple On Same Page

### ISSUE THREAD

**Issue by melloware** [thorst/jquery-idletimer#53]
We had this issue reported: https://github.com/primefaces/primefaces/issues/5084

And a PR submitted to fix the issue: https://github.com/primefaces/primefaces/pull/5083

However the PrimeFaces project would prefer not to customize this component and was wondering if you could add this feature to your core library?   You can review that PR there may be a better way to do it?

Thanks for your attention and support!

**Comment by pazepaze** [comment]
I'd say this is fixed by my pull request now.

**Comment by melloware** [comment]
This was fixed but doesn't seem to be in the dist folder?
